export const ChallengeConfig = {
    1: { name: "Sonar Sweep", exampleOnly: false },
    2: { name: "Dive!", exampleOnly: false },
    3: { name: "Binary Diagnostic", exampleOnly: true },
    4: { name: "Giant Squid", exampleOnly: false },
    5: { name: "Hydrothermal Venture", exampleOnly: false },
    6: { name: "Lanternfish", exampleOnly: false },
    7: { name: "The Treachery of Whales", exampleOnly: true },
    8: { name: "Seven Segment Search", exampleOnly: false },
    9: { name: "Smoke Basin", exampleOnly: true },
    10: { name: "Syntax Scoring", exampleOnly: false },
    11: { name: "Dumbo Octopus", exampleOnly: false },
    12: { name: "Passage Pathing", exampleOnly: false },
    13: { name: "Transparent Origami", exampleOnly: false },
    14: { name: "Extended Polymerization", exampleOnly: false },
    15: { name: "Chiton", exampleOnly: true },
    16: { name: "Packet Decoder", exampleOnly: false },
    17: { name: "Trick Shot", exampleOnly: false },
    18: { name: "Snailfish", exampleOnly: false },
    19: { name: "Beacon Scanner", exampleOnly: true },
    20: { name: "Trench Map", exampleOnly: false },
    21: { name: "Dirac Dice", exampleOnly: false },
    22: { name: "Reactor Reboot", exampleOnly: true },
    23: { name: "Amphipod", exampleOnly: false },
    24: { name: "Arithmetic Logic Unit", exampleOnly: false },
    25: { name: "Sea Cucumber", exampleOnly: true },
};
