import "./globals.css";
import { Inter } from "next/font/google";
import { ErrorBoundary } from "react-error-boundary";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <ErrorBoundary
                    fallback={
                        <div className="h-screen font-serif text-4xl italic center text-zinc-200 bg-zinc-950">
                            fin
                        </div>
                    }
                >
                    {children}
                </ErrorBoundary>
            </body>
        </html>
    );
}
