on:
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: strigoi
          key: ${{ secrets.STRIGOI_PRIVATE_KEY }}
      - run: echo "Hello, world!"